# Generated by Django 4.2.2 on 2023-06-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('precio', models.CharField(blank=True, max_length=50, verbose_name='precio')),
            ],
        ),
    ]
