# Generated by Django 4.2.2 on 2023-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_cliente_boleta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='cliente',
        ),
        migrations.AddField(
            model_name='garden',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
