# Generated by Django 4.2.2 on 2023-07-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_cliente_boleta_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('tipo', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garden.envio'),
        ),
    ]
