# Generated by Django 4.2.2 on 2023-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_envio_boleta_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
